FROM ouankou/rds:threadsanitizer

USER rds
RUN git clone https://github.com/ouankou/rds-tsan.git
RUN git clone https://github.com/World-Worst-Detector/dataracebench.git
RUN cd /home/rds/dataracebench/micro-benchmarks && \
    rm -rf *
COPY ["start.sh", "/home/rds/"]
COPY ["check.sh", "/home/rds/dataracebench/"]

ENTRYPOINT /home/rds/start.sh && /bin/bash
